# Generated by Django 2.2.2 on 2019-06-10 08:48

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django_mysql.models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'passtimejson',
            },
        ),
    ]
