# Generated by Django 2.2.2 on 2019-06-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openNotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ai_analysis_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('success', models.CharField(default=None, max_length=255)),
                ('message', models.CharField(default=None, max_length=255)),
                ('Class', models.IntegerField(default=None)),
                ('confidence', models.DecimalField(decimal_places=4, default=None, max_digits=5)),
                ('request_timestamp', models.PositiveIntegerField(default=None)),
                ('response_timestamp', models.PositiveIntegerField(default=None)),
            ],
            options={
                'db_table': 'ai_analysis_log',
            },
        ),
        migrations.CreateModel(
            name='NewAPIResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.CharField(default=None, max_length=255)),
                ('message', models.CharField(default=None, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('longitude', models.DecimalField(decimal_places=1, default=None, max_digits=4)),
                ('passes', models.IntegerField(default=None)),
                ('request_timestamp', models.PositiveIntegerField(default=None)),
                ('response_timestamp', models.PositiveIntegerField(default=None)),
            ],
            options={
                'db_table': 'Newpasstimejson',
            },
        ),
    ]
