# Generated by Django 2.2.2 on 2019-06-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openNotify', '0002_ai_analysis_log_newapiresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapiresponse',
            name='image_path',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
