# Generated by Django 2.2.2 on 2019-06-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openNotify', '0003_newapiresponse_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newapiresponse',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
