# Generated by Django 2.2.2 on 2019-06-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openNotify', '0004_auto_20190611_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newapiresponse',
            name='image_path',
            field=models.CharField(default=None, max_length=255, verbose_name='イメージパス'),
        ),
    ]
