# Generated by Django 2.2.2 on 2019-06-11 09:13

from django.db import migrations
import django_mysql.models
import openNotify.models


class Migration(migrations.Migration):

    dependencies = [
        ('openNotify', '0005_auto_20190611_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresponse',
            name='data',
            field=django_mysql.models.JSONField(default=openNotify.models.my_default),
        ),
    ]
