# Generated by Django 2.2.2 on 2019-06-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openNotify', '0006_auto_20190611_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiresponse',
            old_name='data',
            new_name='jsondata',
        ),
    ]
