# Generated by Django 2.2.2 on 2019-06-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openNotify', '0007_auto_20190611_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiresponse',
            name='jsondata',
        ),
    ]
