# Generated by Django 2.2.2 on 2019-06-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openNotify', '0009_auto_20190611_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newapiresponse',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
